version: '3'

services:
  library:
    image: postgres:14.5
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: BAKHANKOVA_215
      POSTGRES_PASSWORD: pass1
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  station1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: station1
      POSTGRES_USER: BAKHANKOVA_215
      POSTGRES_PASSWORD: pass2
    volumes:
      - ./docker/db/scripts/station1:/docker-entrypoint-initdb.d
    ports:
      - "5435:5435"
  station2:
    image: postgres:14.5
    environment:
      POSTGRES_DB: station2
      POSTGRES_USER: BAKHANKOVA_215
      POSTGRES_PASSWORD: pass3
    volumes:
      - ./docker/db/scripts/station2:/docker-entrypoint-initdb.d
    ports:
      - "5434:5434"
